### ISSUE TITLE
Nuget Licence info

### ISSUE THREAD

**Issue by Julie-House** [yuzd/HttpClientFactory#5]
Please can you add the license link to the nuget info page? our licence scanning tool is insisting this package isn't licenced.

Thanks

**Comment by yuzd** [comment]
ok ! 
I will do it tomorrow

**Comment by yuzd** [comment]
1.0.4

![image](https://dimg04.c-ctrip.com/images/0v54q120009iri4sz60A1.png)

**Comment by Julie-House** [comment]
Excellent thanks
