### ISSUE TITLE
Wrong placement of MIT Licence

### ISSUE THREAD

**Issue by jbonnett92** [yuzd/HttpClientFactory#6]
Hi,
The MIT Licence file pops up in my project structure, making my personal project MIT, can you fix this please?

Thanks
Jamie

**Comment by yuzd** [comment]
I haven't encountered the scene you mentioned, do you have a corresponding screenshot?

**Comment by jbonnett92** [comment]
Hi,
I'm not sure if by marking it as completed you fixed it, though it is not fixed.
Here is the screenshot:
<img width="1470" alt="Screenshot 2023-06-07 at 14 50 08" src="https://github.com/yuzd/HttpClientFactory/assets/3740700/f72d23dc-b8db-49ba-9451-de597f694135">

Thanks,
Jamie

**Comment by yuzd** [comment]
i see , will fix later

**Comment by yuzd** [comment]
@jbonnett92 check version 1.0.5
